FROM debian:jessie

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    git \
    openssh-client \
    rsync \
    vim \
  && rm -rf /var/lib/apt/lists/*
