FROM alpine:3.4
RUN apk add --no-cache \
  bash \
  ca-certificates \
  curl \
  git \
  openssl \
  openssh-client \
  py-httplib2 \
  py-jinja2 \
  py-paramiko \
  py-pip \
  py-yaml \
  python \
  rsync \
  sudo

RUN pip install ansible==2.1.3.0

ENTRYPOINT ["ansible"]
