FROM briceburg/ansible:2.1-dex

#
# dex ansible:2.1-dex-docker
#

RUN apk add --no-cache \
  docker


# docker-machine
RUN curl -L https://github.com/docker/machine/releases/download/v0.9.0-rc2/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && \
  chmod +x /usr/local/bin/docker-machine

# docker-compose
RUN pip install docker-compose==1.9.0

#
# v1 dex-api
#

LABEL \
  org.dockerland.dex.host_docker="rw"
